
image: python:3.13

stages:
  - build
  - pages

before_script:
    - apt-get update --yes
    - apt-get install --yes cmake
    - apt-get install --yes libblas3 liblapack3 liblapack-dev libblas-dev
    - pip install virtualenv
    - python -m venv .venv
    - source .venv/bin/activate

cache:
  key: pip-global-cache
  paths:
    - $CI_PROJECT_DIR/.cache/pip

build:
  stage: build
  rules:
  - if: '$CI_COMMIT_BRANCH == "docs"'
    when: never
  - when: always

  script:
    - export CMAKE_BUILD_PARALLEL_LEVEL=2
    - export PARALLEL_BUILD_TTNPP=2
    - python -m pip -v install .[lint,test]

    - ruff check .
    - python -m pytest -n 2 tests

pages:
  stage: pages
  rules:
  - if: '$CI_COMMIT_BRANCH == "docs" || $CI_COMMIT_BRANCH == "main"'
    when: always
  - when: never

  script:
    - echo $CI_REPOSITORY_URL
    - echo "The site will be deployed to $CI_PAGES_URL"
    - apt-get install --yes pandoc
    - export CMAKE_BUILD_PARALLEL_LEVEL=4
    - export PARALLEL_BUILD_TTNPP=8
    - python -m pip -v install .[docs]
    - cd docs
    - make html
    - cp -r build/html ../public
    - cd ../
  artifacts:
    paths:
      - public
