image: python:3.13

stages:
  - build
  - lint
  - test

before_script:
    - apt-get update --yes
    - apt-get install --yes cmake
    - apt-get install --yes libblas3 liblapack3 liblapack-dev libblas-dev
    - pip install virtualenv
    - python -m venv .venv
    - source .venv/bin/activate

build:
  stage: build
  script:
    - export CMAKE_BUILD_PARALLEL_LEVEL=4
    - export PARALLEL_BUILD_TTNPP=8
    - python -m pip -v install .

  artifacts:
    paths:
        - /builds/quantum-software/pyttn/pyttn/
lint:
  stage: lint
  script:
    - python -m pip -v install .[lint]
    - export SKIP_BUILD_TTNPP_LIBRARY=True
    - ruff check

test:
  stage: test
  script:
    - python -m pip -v install .[test]
    - export SKIP_BUILD_TTNPP_LIBRARY=True
    - python -m pytest

