# This files is part of the pyTTN package.
# (C) Copyright 2025 NPL Management Limited
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

from typing import List, Tuple

import numpy as np
from ..ttns.ntreeExt import ntree
from ..ttns.topology_tree import TopoTree
from ..sop.system_information import SystemInfo
from .interaction_graph import InteractionGraph

def compute_tree_cut_metrics(tree : ntree, M: np.ndarray, local_dims: list[int]):
    """Compute cut metrics for every node in an ntree.

    The cut associated with a node corresponds to the partition induced by removing the edge connecting the node to its parent.  The returned metrics are indexed by the ntree path of each node.

    :param tree: The ntree object
    :type tree: ntree
    :param M: Dense interaction matrix
    :type M: np.ndarray
    :param local_dims: Local Hilbert-space dimensions of the physical modes
    :type local_dims: list[int]

    :returns: Dictionary containing cut information for every node
    :rtype: dict
    """

    N = M.shape[0]

    if len(local_dims) != N:
        raise ValueError("Length of local_dims must match the size of M.")

    all_sites = np.arange(N)
    total_log2_lhd = np.sum(np.log2(local_dims))

    metrics = {}
    for node in tree.dfs():
        # Physical modes contained in subtree
        sites = np.array(sorted(node.at(ind).value for ind in node.leaf_indices()),dtype=int,)
        nleaves = len(sites)
        subtree_log2_lhd = float(np.sum(np.log2(np.asarray(local_dims)[sites])))

        complement_log2_lhd = (total_log2_lhd - subtree_log2_lhd)

        chi_upper_bound_log2 = min(subtree_log2_lhd, complement_log2_lhd)

        if node.is_root():
            cut_weight = 0.0
        else:
            mask = np.ones(N, dtype=bool)
            mask[sites] = False
            complement = all_sites[mask]
            cut_weight = float(M[np.ix_(sites, complement)].sum())

        metrics[tuple(node.index())] = { "cut_weight": cut_weight, "nleaves": nleaves, "subtree_log2_lhd": subtree_log2_lhd, "complement_log2_lhd": complement_log2_lhd, "chi_upper_bound_log2": chi_upper_bound_log2}

    return metrics

def propose_bond_dimensions(metrics: dict, min_chi: int = 8, max_chi: int = 64):
    """Propose minimum and maximum bond dimensions for TTN calculations.

    :param metrics: Tree cut metrics generated by :func:`compute_tree_cut_metrics`
    :type metrics: dict
    :param min_chi: Minimum bond dimension scale used when assigning bond dimensions to weakly interacting cuts
    :type min_chi: int
    :param max_chi: Maximum bond dimension scale used when assigning bond dimensions to strongly interacting cuts
    :type max_chi: int

    :returns: Dictionary containing the proposed minimum and maximum bond dimensions for each node, along with supplementary information used in their construction
    :rtype: dict
    """

    if min_chi < 1:
        raise ValueError("min_chi must be positive")

    if max_chi < min_chi:
        raise ValueError("max_chi must be greater than min_chi")

    cuts = [m["cut_weight"] for m in metrics.values() if m["cut_weight"] > 0]

    max_cut = max(cuts) if cuts else 1.0
    temp = {}

    for node, data in metrics.items():
        if data["cut_weight"] <= 0:
            physical_limit = int(min(np.floor(2**min(data["chi_upper_bound_log2"],60)),np.iinfo(np.int64).max))
            temp[node] = {"max": min(2, physical_limit), "limit": physical_limit}
            continue

        importance = np.log1p(data["cut_weight"])/ np.log1p(max_cut)
        log2_chi = (1.0 - importance) * np.log2(min_chi) + importance * np.log2(max_chi)
        proposed_max = int(np.round(2**log2_chi))
        physical_limit = int(min(np.floor(2**min(data["chi_upper_bound_log2"],60)),np.iinfo(np.int64).max))
        temp[node] = {"max": proposed_max, "limit": physical_limit}


    largest_unsaturated = 0

    for vals in temp.values():
        raw = vals["max"]
        limit = vals["limit"]

        if raw < limit:
            largest_unsaturated = max(largest_unsaturated,raw)

    scale = max_chi / largest_unsaturated  if largest_unsaturated > 0 else 1.0

    result = {}

    for node, vals in temp.items():
        if vals["max"] <= 1:
            floor = min(2, vals["limit"])
            result[node] = {"min_chi": floor, "max_chi": floor}
            continue
        physical_limit = vals["limit"]
        proposed_max = int(np.round(vals["max"] * scale))

        proposed_max = min(proposed_max, physical_limit, max_chi)

        proposed_min = max(2, min_chi, int(np.sqrt(proposed_max))//4)
        proposed_min = min(proposed_min, physical_limit)
        proposed_max = max(proposed_min, proposed_max)
        result[node] = {"min_chi": proposed_min, "max_chi": proposed_max}
    return result


def bond_dimension_inputs(topology: TopoTree, sysinfo: SystemInfo, graph: InteractionGraph) -> Tuple[np.ndarray, List[int]]:
    """Build inputs for :func:`compute_tree_cut_metrics` from a topology tree.

    Returns the interaction matrix and local Hilbert-space dimensions indexed by
    the current leaves of ``topology``. Composite-mode leaves use dimensions and
    interaction weights from ``sysinfo`` and ``graph``; all other leaves are
    assigned dimension 1 and zero interaction weight.

    :param topology: The topology tree to build cut-metric inputs for
    :type topology: TopoTree
    :param sysinfo: System information used to determine local Hilbert space dimensions
    :type sysinfo: SystemInfo
    :param graph: The interaction graph used to look up edge weights between leaves
    :type graph: InteractionGraph
    :return: The ``(M, local_dims)`` pair, indexed by ``topology``'s raw leaf values
    :rtype: tuple[np.ndarray, list[int]]
    """
    n = topology.tree.nleaves()
    label_to_raw = {label: topology.tree.at(path).value for label, path in topology.leaf_paths().items()}

    graph_labels, graph_W = graph.weight_matrix()
    graph_index = {lx: i for i, lx in enumerate(graph_labels)}

    M = np.zeros((n, n))
    local_dims = [1] * n
    for li, pi in label_to_raw.items():
        if li in sysinfo:
            local_dims[pi] = sysinfo.local_dim(li)
        if li not in graph_index:
            continue
        gi = graph_index[li]
        for lj, pj in label_to_raw.items():
            if lj in graph_index:
                M[pi, pj] = graph_W[gi, graph_index[lj]]
    return M, local_dims